"""empty message

Revision ID: 95524fd016f3
Revises: b2cbdbf4f413
Create Date: 2021-11-19 20:26:20.647747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95524fd016f3'
down_revision = 'b2cbdbf4f413'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('created_time', sa.DateTime(), nullable=True))
    op.add_column('venues', sa.Column('created_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'created_time')
    op.drop_column('artists', 'created_time')
    # ### end Alembic commands ###
